version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: webloan_mongo
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webloan_backend
    ports:
      - "3001:3000" # Cambiado a 3001 para evitar posibles conflictos
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      PAYLOAD_SECRET: ${PAYLOAD_SECRET:-A_SUPER_SECURE_SECRET_KEY_FOR_PAYLOAD} # ¡CAMBIA ESTO EN PRODUCCIÓN!
      NODE_ENV: production
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webloan_frontend
    ports:
      - "5000:3000" # Mapea el puerto 3000 del contenedor a 5000 en el host para evitar conflicto con el backend
    environment:
      NEXT_PUBLIC_REST_API_ENDPOINT: http://148.113.136.150:3001 # URL pública del backend para el frontend
      PORT: 3000 # Puerto interno del contenedor Next.js
      NODE_ENV: production
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:
