export const ROUTES = {
  HOME: '/',
  PRODUCT: `/productos`,
  CHECKOUT: '/checkout',
  CONTACT: '/contactenos',
  TERMS: '/terminos-y-condiciones',
  PRIVACY: '/politicas-de-privacidad',
  FAQ: '/preguntas',
  FORGET_PASSWORD: '/forget-password',
  CHANGE_PASSWORD: '/nueva-contrasena',
  ACCOUNT: '/my-account/configuracion',
  ORDERS: '/my-account/ordenes',
  ACCOUNT_SETTING: '/my-account/configuracion',
  ADDRESS: '/my-account/direcciones',
  PAYMENT: '/my-account/payment',
  HELP_CENTER: '/my-account/centro-de-ayuda',
  LEGAL_NOTICE: '/my-account/aviso-legal',
  NOTIFICATION: '/my-account/notification',
  SHOPS: '/sucursales',
  LOGIN: '/iniciar-sesion',
  SIGN_UP: '/registrarse',
  SEARCH: '/buscar',
  PRODUCTS: '/productos',
  BUNDLE: '/bundles',
  CATEGORY: '/category',
  ORDER: '/completar-orden',
};
